version: "3"
services:
  homeassistant:
    container_name: homeassistant
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - /etc/localtime:/etc/localtime:ro
    privileged: true
