- platform: generic_thermostat
  name: Bedroom
  heater: switch.bedroom_heating_switch
  unique_id: bedroom-thermostat
  min_temp: 4
  max_temp: 35
  target_sensor: sensor.bedroom_sensor_air_temperature
  away_temp: 4
  sleep_temp: 19
  cold_tolerance: 0.3
  comfort_temp: 20
  initial_hvac_mode: "heat"

- platform: generic_thermostat
  name: Gym
  heater: switch.gym_heating_switch
  unique_id: gym-thermostat
  min_temp: 4
  cold_tolerance: 0.3
  max_temp: 35
  target_sensor: sensor.gym_sensor_air_temperature
  away_temp: 4
  comfort_temp: 20
  initial_hvac_mode: "heat"

- platform: generic_thermostat
  name: Living Room
  heater: switch.living_room_heating_switch
  unique_id: living-room-thermostat
  min_temp: 4
  max_temp: 35
  target_sensor: sensor.living_room_sensor_air_temperature
  sleep_temp: 4
  cold_tolerance: 0.3
  away_temp: 4
  comfort_temp: 20
  initial_hvac_mode: "heat"

- platform: generic_thermostat
  name: Boiler
  heater: switch.boiler
  unique_id: boiler
  min_temp: 4
  max_temp: 45
  target_sensor: sensor.boiler_boost_temperature
  target_temp: 25
  min_cycle_duration:
    seconds: 30
  sleep_temp: 4
  cold_tolerance: 0.3
  away_temp: 4
  comfort_temp: 21
  initial_hvac_mode: "off"
