automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
template: !include template.yaml
climate: !include climate.yaml
frontend: !include frontend.yaml
switch: !include switch.yaml
intent_script: !include intent-scripts.yaml
ios: !include ios.yaml

logger:
  default: debug

rest_command:
  shutdown_imac:
    url: "http://bens-imac.local:8084/shutdown"
    method: POST

proximity:
  home:
    tolerance: 50
    unit_of_measurement: m
    devices:
      - person.ben_wainwright

service: tts.speak
target:
  entity_id: tts.living_room
data:
  media_player_entity_id: media_player.living_room_speaker
  message: "May the force be with you."

lovelace:
  resources:
    - url: /local/lovelace-card-tools/card-tools.js
      type: module
    - url: /local/community/lovelace-mushroom/mushroom.js
      type: module
    - url: /local/js/bounce.js
      type: module
  dashboards:
    mobile-dashboard:
      mode: yaml
      filename: dashboards/mobile.yaml
      show_in_sidebar: true
      title: Mobile
    main-dashboard:
      mode: yaml
      filename: dashboards/main.yaml
      show_in_sidebar: true
      title: Main

# Loads default set of integrations. Do not remove.
default_config:

shell_command:
  imac_off: ssh bennonadmin@bens-imac.local shutdown -h now
  update_config: cd /config && git pull origin main

input_boolean:
  in_bed:
    name: In Bed
    icon: mdi:bed
    initial: false
  done_good_morning:
    name: Have I had my good morning message

recorder:
  db_url: !secret mariadb_url

notify:
  - name: email
    platform: smtp
    server: smtp.gmail.com
    sender: bwainwright28@gmail.com
    recipient: bwainwright28@gmail.com
    port: 587
    timeout: 15
    sender_name: Ben Wainwright
    username: bwainwright28@gmail.com
    password: !secret gmail_password
    encryption: starttls

wake_on_lan:

# Text to speech
tts:
  - platform: google_translate

# Dummy entity to enable logging that I can filter
sensor:
  - platform: template
    sensors:
      automation_log_entity:
        unique_id: "node-red-logging-entity"
        friendly_name: "Node Red Logging"
        value_template: "on"

homeassistant:
  auth_providers:
    - type: trusted_networks
      trusted_networks:
        - 192.168.1.0/24
        - 127.0.0.1
        - ::1
      trusted_users:
        192.168.1.121: 9a9adad4cf9f4877a677481fdb37f6bd
        127.0.0.1: 9a9adad4cf9f4877a677481fdb37f6bd
        "2a01:4b00:d220:f100:d08a:a9f3:8ce6:5d28": 9a9adad4cf9f4877a677481fdb37f6bd
      allow_bypass_login: true
    # - type: homeassistant

  name: Home
  latitude: 53.4791973
  longitude: -2.2213431
  elevation: 54
  unit_system: metric
  currency: GBP
  country: GB
  time_zone: "Europe/London"
  external_url: "https://home.benwainwright.me/"
  internal_url: "http://homeassistant.local"

device_sun_light_trigger:
  light_group: light.living_room_2
  light_profile: relax
  device_group: group.ben

zone:
  - name: Home
    latitude: 53.4791973
    longitude: -2.2213431
    radius: 35
    icon: mdi:account-multiple

group:
  ben:
    name: "Ben"
    entities:
      - person.ben_wainwright
