- platform: template
  switches:
    living_room_tv_on:
      unique_id: living_room_tv_on
      value_template: "{{ is_state('media_player.lg_webos_smart_tv', 'on') }}"
      turn_on:
        service: wake_on_lan.send_magic_packet
        data:
          mac: 64:95:6C:49:51:E0
      turn_off:
        service: media_player.turn_off
        target:
          entity_id: media_player.lg_webos_smart_tv

- platform: template
  switches:
    imac_pro_on:
      unique_id: imac_pro_on
      turn_on:
        service: wake_on_lan.send_magic_packet
        data:
          mac: 88:66:5a:04:3d:53
      turn_off:
        service: rest_command.shutdown_imac
