turn_tv_on:
  alias: Turn TV On
  sequence:
    - service: wake_on_lan.send_magic_packet
      data:
        broadcast_port: 9
        mac: 2C:2B:F9:57:E7:2E
  mode: single
  icon: mdi:television
turn_everything_off:
  alias: Turn Everything Off
  sequence:
    - service: rest_command.shutdown_imac
      data: {}
      alias: Turn off iMac
    - service: light.turn_off
      data: {}
      target:
        area_id:
          - main_bathroom
          - en_suite
          - bedroom
          - gym
          - hallway
          - living_room
      alias: Turn Lights Off
    - service: media_player.media_pause
      data: {}
      target:
        area_id:
          - bedroom
          - gym
          - living_room
      alias: Pause Music
    - service: switch.turn_off
      data: {}
      target:
        entity_id: switch.living_room_tv_on
      alias: Turn TV Off
  mode: single
  icon: mdi:power
