homeassistant: true
mqtt:
  server: mqtt://core-mosquitto:1883
  user: addons
  password: emeilachaeBeloh5ooRodaiNgeicooYaey5ig9boovooy7looR8eir7Uhahvengi
serial:
  port: /dev/ttyUSB0
frontend:
  port: 8099
advanced:
  homeassistant_legacy_entity_attributes: false
  legacy_api: false
  legacy_availability_payload: false
device_options:
  legacy: false
devices:
  '0x001788010cd820ed':
    friendly_name: Bathroom Motion Sensor
  '0x001788010cd84294':
    friendly_name: Hallway Motion Sensor
